version: '3'
services:
  kkfileview:
    image: keking/kkfileview:4.1.0
    environment:
      - KK_OFFICE_PREVIEW_SWITCH_DISABLED=true
      - KK_MEDIA_CONVERT_DISABLE=true
      - KK_MEDIA=
      - KK_FILE_UPLOAD_ENABLED=true
      - WATERMARK_TXT=Online Learning System
      - KK_CACHE_ENABLED=true
    networks:
      local:
        ipv4_address: 192.168.20.10

  openresty:
    build: kkfileview-nginx
    ports:
      - "8012:8012"
    volumes:
      - ./logs/openresty:/usr/local/openresty/nginx/logs
    depends_on:
      - kkfileview
    networks:
      local:
        ipv4_address: 192.168.20.12

  redis:
    image: redis:5.0.5
    networks:
      local:
        ipv4_address: 192.168.20.13

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - kkfileview
    networks:
      local:
        ipv4_address: 192.168.20.11

networks:
  local:
    ipam:
      config:
        - subnet: 192.168.20.0/24
